#!/bin/bash
chcon -Rt svirt_sandbox_file_t $PWD
docker run -d -p 80:80 --name=$1 \
           -v $PWD/Kinetic-Rules-Engine:/web/lib/perl \
           -v $PWD/kre_config:/web/etc \
           -v $PWD/logs:/web/logs \
           -v $PWD/mongo:/var/lib/mongo \
           windley/kre02
